export enum MessageType {
  CHECK_EXTENSION = "CHECK_EXTENSION",
  FETCH_PROFILE = "FETCH_PROFILE",
  FETCH_CONNECTIONS = "FETCH_CONNECTIONS",
  FETCH_SEARCH = "FETCH_SEARCH",
  SEARCH_PROFILES = "SEARCH_PROFILES",
  ERROR = "ERROR",
}
